import React from "react";
import { Link } from "react-router-dom";

const TermsAndConditions = () => {
  const pageStyle = {
    backgroundColor: "#27001a",
    color: "white",
    minHeight: "100vh",
    padding: "50px 8vw",
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    lineHeight: "1.8",
  };

  const containerStyle = {
    maxWidth: "960px",
    margin: "0 auto",
    backgroundColor: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(173,149,81,0.3)",
    borderRadius: "12px",
    padding: "50px 55px",
    boxShadow: "0 10px 40px rgba(0,0,0,0.5)",
  };

  const titleStyle = {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: "34px",
    color: "#d4be82",
    marginBottom: "8px",
    textAlign: "center",
    letterSpacing: "1px",
  };

  const subTitleStyle = {
    fontSize: "14px",
    color: "rgba(255,255,255,0.55)",
    textAlign: "center",
    marginBottom: "35px",
    borderBottom: "1px solid rgba(212,190,130,0.2)",
    paddingBottom: "20px",
  };

  const sectionHeading = {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: "18px",
    color: "#ad9551",
    marginTop: "30px",
    marginBottom: "10px",
  };

  const subHeading = {
    fontSize: "15px",
    color: "#d4be82",
    marginTop: "18px",
    marginBottom: "8px",
    fontWeight: "600",
  };

  const para = {
    fontSize: "14px",
    color: "rgba(255,255,255,0.82)",
    marginBottom: "14px",
    textAlign: "justify",
  };

  const divider = {
    borderColor: "rgba(173,149,81,0.2)",
    margin: "25px 0",
  };

  const backTop = {
    display: "inline-block",
    fontSize: "12px",
    color: "#d4be82",
    cursor: "pointer",
    marginTop: "6px",
    marginBottom: "20px",
    letterSpacing: "0.3px",
  };

  const scrollToTop = () => window.scrollTo({ top: 0, behavior: "smooth" });

  return (
    <div style={pageStyle}>
      <div style={containerStyle}>
        <h1 style={titleStyle}>Terms and Conditions</h1>
        <p style={subTitleStyle}>
          Please read these Terms and Conditions carefully before using the Bencham Jewellers website.
          <br />
          <span style={{ fontSize: "12px" }}>Last Updated: August 2026</span>
        </p>

        <p style={para}>
          This record is generated by a computer system and does not require physical or digital signatures.
        </p>

        {/* 1 */}
        <h2 style={sectionHeading}>1. INTRODUCTION</h2>
        <p style={para}>
          Welcome to <strong>Bencham Jewellers</strong> (hereinafter referred to as "we", "us", "our", or "Bencham"). We are a premium online gemstone jewelry marketplace and these are the terms and conditions governing your access to and use of Bencham, including its website, related sub-domains, services, and tools (the "Site").
        </p>
        <p style={para}>
          By using the Site, you accept and agree to be bound by these Terms and Conditions. This agreement is effective upon your use of the Site. If you do not agree, please do not access or use this Site. Bencham reserves the right to change or update these Terms at any time without prior notice. Please check regularly for updates.
        </p>

        <hr style={divider} />

        {/* 2 */}
        <h2 style={sectionHeading}>2. CONDITIONS OF USE</h2>

        <h3 style={subHeading}>A. YOUR ACCOUNT</h3>
        <p style={para}>
          To access certain services on the Site, you may be required to register an account. You are fully responsible for maintaining the confidentiality of your login credentials, password, and all activities conducted under your account. You must notify us immediately if you suspect unauthorized access or misuse of your account.
        </p>
        <p style={para}>
          All personal details provided must be accurate and kept up to date. We reserve the right to suspend or terminate accounts that violate these Terms or provide misleading information.
        </p>

        <h3 style={subHeading}>B. PRIVACY</h3>
        <p style={para}>
          Your personal data is treated with strict confidentiality. Information collected during your use of the Site is governed by applicable laws of Sri Lanka. By using the Site, you consent to the collection and use of your data as described in our Privacy Policy.
        </p>

        <h3 style={subHeading}>C. PLATFORM FOR COMMUNICATION</h3>
        <p style={para}>
          Bencham Jewellers provides an online platform enabling you to browse, select, and purchase handcrafted gemstone jewelry. By using this Site, you consent to receive transactional and promotional communications via email, SMS, or phone call.
        </p>

        <h3 style={subHeading}>D. SITE ACCESS AND LICENSE</h3>
        <p style={para}>
          We grant you a limited, non-transferable, and revocable license to use this Site solely for personal shopping purposes. You may not reproduce, duplicate, resell, or commercially exploit any portion of the Site without our express written consent. You must not use this Site for any unlawful purposes or activities that may harm or impair the Site or other users.
        </p>

        <h3 style={subHeading}>E. INTELLECTUAL PROPERTY AND TRADEMARKS</h3>
        <p style={para}>
          Bencham Jewellers, our logos, product photography, design elements, scripts, and all content published on this Site are the exclusive intellectual property of Bencham Jewellers and are protected under Sri Lankan copyright and trademark laws. Unauthorized use or reproduction is strictly prohibited.
        </p>
        <span style={backTop} onClick={scrollToTop}>&#8593; Back to Top</span>

        <hr style={divider} />

        {/* 3 */}
        <h2 style={sectionHeading}>3. CONDITIONS OF SALE</h2>

        <h3 style={subHeading}>A. GEMSTONE AND PRODUCT DESCRIPTIONS</h3>
        <p style={para}>
          Bencham Jewellers takes great care to represent each ethically sourced natural gemstone and handcrafted piece accurately, including specifications such as carat weight, gemstone type, and gold purity (18K / 22K gold). However, natural gemstones inherently feature unique color gradations, natural inclusions, and optical variations that may appear slightly different from product photography due to lighting conditions. Full specifications are available on each Product Details page.
        </p>

        <h3 style={subHeading}>B. PRICING AND AVAILABILITY</h3>
        <p style={para}>
          All prices are listed in Sri Lankan Rupees (LKR), inclusive of applicable taxes. Bencham Jewellers reserves the right to correct any pricing errors at any time. Adding an item to your cart does not guarantee the price shown at that time. We reserve the right to cancel orders in the event of pricing discrepancies.
        </p>

        <h3 style={subHeading}>C. ORDER PROCESSING AND DISPATCH</h3>
        <p style={para}>
          When you place an order on our Site, order acceptance is confirmed when the product is dispatched. Dispatch timelines are estimates and subject to third-party delivery service schedules. We will communicate any delays via email or SMS. You may cancel your order at no cost prior to dispatch under <strong>My Account &rarr; My Orders</strong>.
        </p>

        <h3 style={subHeading}>D. RETURNS AND EXCHANGES</h3>
        <p style={para}>
          Delivered items may be returned within <strong>7 business days</strong> of delivery, subject to the following conditions:
        </p>
        <ul style={{ fontSize: "14px", color: "rgba(255,255,255,0.82)", marginBottom: "14px", paddingLeft: "20px", lineHeight: "1.9" }}>
          <li>The item must be in its original, unworn condition with all original packaging intact.</li>
          <li>Proof of purchase (order number) must be provided.</li>
          <li>Custom or personalized pieces are non-refundable unless defective.</li>
          <li>Items damaged or defective upon delivery are eligible for replacement at no extra cost.</li>
        </ul>
        <p style={para}>
          To submit a return request, navigate to <strong>My Account &rarr; My Orders &rarr; Request Return</strong>. Our team will contact you within 2&ndash;3 business days.
        </p>

        <h3 style={subHeading}>E. CUSTOMER REVIEWS</h3>
        <p style={para}>
          Verified purchasers who have received their delivered orders may submit product reviews and star ratings. By submitting a review, you grant Bencham Jewellers the right to display and use that review content on the Site. Reviews must be honest, relevant, and must not contain offensive or defamatory content. Bencham reserves the right to remove any review that violates these standards.
        </p>
        <span style={backTop} onClick={scrollToTop}>&#8593; Back to Top</span>

        <hr style={divider} />

        {/* 4 */}
        <h2 style={sectionHeading}>4. DISCLAIMER</h2>
        <p style={para}>
          You acknowledge that you are accessing the Site and transacting at your own risk. While we strive to maintain accurate product information, Bencham Jewellers expressly disclaims all warranties, express or implied, regarding the accuracy, completeness, or suitability of information on the Site. We are not liable for any direct, indirect, or consequential losses arising from the use of the Site.
        </p>

        <hr style={divider} />

        {/* 5 */}
        <h2 style={sectionHeading}>5. GOVERNING LAW AND JURISDICTION</h2>
        <p style={para}>
          These Terms and Conditions are governed by the laws of <strong>The Democratic Socialist Republic of Sri Lanka</strong>. Any disputes arising from the use of this Site shall be subject to the exclusive jurisdiction of the competent courts of Sri Lanka.
        </p>
        <span style={backTop} onClick={scrollToTop}>&#8593; Back to Top</span>

        <hr style={divider} />

        {/* 6 */}
        <h2 style={sectionHeading}>6. CONTACT US</h2>
        <p style={para}>
          For any questions or concerns regarding these Terms and Conditions, please visit our{" "}
          <Link to="/contact" style={{ color: "#d4be82", textDecoration: "underline" }}>
            Contact Us
          </Link>{" "}
          page. Our customer support team is happy to assist you.
        </p>

        <div style={{ textAlign: "center", marginTop: "35px", paddingTop: "20px", borderTop: "1px solid rgba(173,149,81,0.2)", color: "rgba(255,255,255,0.4)", fontSize: "12px" }}>
          &copy; 2026 Bencham Jewellers. All Rights Reserved.
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;

